name: device_info_plus_platform_interface
description: A common platform interface for the device_info_plus plugin.
version: 7.0.2
publish_to: none
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_lints: ">=5.0.0 <6.0.0"
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.3"
